### PR TITLE
fixed the logo and icon

### PR DESCRIPTION
**Pull request by linzof**
fixed issue 21 

installed file loader to the package

fixed favicon with size 96x96

changed the manifest.json from "." to "/" seems to be a common issue I come across 

updated some closing tags on the import as well as app.js

{component} was not being used but was declared - on save my ide corrects this.

### CODE REVIEW

**Comment by toth2000** [comment]
@linzof sorry for the late reply, I was busy with my semester exam. Please resolve the conflicts, did you fetch the changes on your forked repo and then pull it in your local machine before you started working? maybe this is the reason for the conflicts.

**Review by toth2000 — APPROVED** [review]
Looks good to me. The Logo on the info bar just looks super cool. Thanks again for such an awesome contribution. Keep up the good work!.

**Comment by linzof** [comment]
Thanks, sir! I didn't want to throw this in the app so it can remain as lite as possible. If we ever need to go back into the files, the illustrator zip is here.

[chatbit_designFiles.zip](https://github.com/toth2000/chatBit/files/6895160/chatbit_designFiles.zip)

**Comment by toth2000** [comment]
> Thanks, sir! I didn't want to throw this in the app so it can remain as lite as possible. If we ever need to go back into the files, the illustrator zip is here.
> 
> [chatbit_designFiles.zip](https://github.com/toth2000/chatBit/files/6895160/chatbit_designFiles.zip)

@linzof Everything is working fine and you did a great work!! I really like the logo and the way you styled it in the InfoBar, this is just awesome. And I am still a learner, so please don't call me sir. Have a great day ahead, cheers mate!

**Pull request merged**
