### PR TITLE
Resolving Last Typo error

### PR DESCRIPTION
**Pull request by AbhishekSharma-86**
``` 
<title>ChatBit</title>

### CODE REVIEW

**Review by toth2000 — APPROVED** [review]
Looks good to me

**Comment by toth2000** [comment]
@AbhishekSharma-86 Thanks for contributing to this project. You did great work, I am merging your PR. ✨

**Comment by AbhishekSharma-86** [comment]
Thanks you sir,
It was amazing working with this project,
It was not too big issue but it means a lot and may help me through my open
source journey

**Comment by toth2000** [comment]
@AbhishekSharma-86 You will do great in open source, all the best!

**Pull request merged**
