### PR TITLE
Display Username then Message

### PR DESCRIPTION
**Pull request by calvinmorett**
- Set order of the classes to display the username before message in div with the classes: messageContainer / justifyStart

### CODE REVIEW

**Review by toth2000 — APPROVED** [review]
Looks good to me.

**Comment by toth2000** [comment]
@calvinmorett Merging the PR into the main branch. Thanks for contributing.

**Comment by calvinmorett** [comment]
Issue: It still display the message then username for other users messages.

**Comment by toth2000** [comment]
> @toth2000 Issue: It still displays the message then username for other users messages.
> image

This is because I have not updated the website on the GH pages. I will update it tomorrow. Actually, I am working on a GitHub action to automate this process.

**Pull request merged**
